Add Docker build
ollama-webui/ollama-webui-lite pull request #17
Opened 2024-01-26 10:45 UTC by Poulpatine

This MR aims to build an ollama-webui-lite docker image for:
- main
- dev
- tags

It adds a Github workflow and a Dockerfile.

2024-01-27 08:20 UTC, tjbck requested changes

2024-01-27 08:20 UTC, tjbck commented on Dockerfile
> +CMD [ "npm", "run", "dev"]
Thanks for the PR! we might want to use something like: https://www.npmjs.com/package/http-server instead of serving the webui using `npm run dev`!

2024-01-30 17:04 UTC, dangminhduc1101 commented
Thanks for the PR. Please provides extra context and justification for this PR, as Docker support is not considered a core functionality of ollama-webui-lite

2024-01-31 09:13 UTC, Poulpatine commented
The notion behind this evolution is to offer users an immediate Docker image, specifically designed for seamless integration with container orchestration platforms like Docker Compose
and Kubernetes.

2024-02-05 23:45 UTC, closed without merging